from ubuntu:latest

run apt-get update
run apt-get install python-dev python3-pip -y

run pip3 install tensorflow
run pip3 install keras==2.0.9
run pip3 install numpy
run pip3 install pandas

workdir /root
